database: &database
  db.username: postgres
  db.password: postgres
  db.host: db

mailer: &mailer
  mailer.host: localhost
  mailer.port: '3000'

development:
  <<: *database
  <<: *mailer

test:
  <<: *database
  <<: *mailer
